// openPullRequest.ts
// Automatically creates a GitHub Pull Request with an AI-generated code patch
// Called by Self-Debug AI when a fix is ready to be reviewed by CodeRabbit

const REPO = "KieranSimpee/nexus-command-hub";
const NEXUS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJraWVyYW5ANXNlbnNlcy5nbG9iYWwiLCJleHAiOjE3ODc0MDg1NTMsImlhdCI6MTc3OTYzMjU1M30.feQst8q8CvGtFAlpy-Yl6Gp7qKVw84FPsbrK2oUAhFg";
const NEXUS_APP = "6a1c237bd9f5ff04b6ac7a73";
const BASE_URL = `https://app.base44.com/api/apps/${NEXUS_APP}/entities`;

const ghRequest = async (path: string, method: string, token: string, body?: object) => {
  const res = await fetch(`https://api.github.com/repos/${REPO}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  return res.json();
};

const postToNexus = async (entity: string, data: Record<string, unknown>) => {
  const res = await fetch(`${BASE_URL}/${entity}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${NEXUS_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(data),
  });
  return { ok: res.ok, status: res.status };
};

export default async function handler(req: Request): Promise<Response> {
  try {
    const body = await req.json().catch(() => ({}));

    // Required inputs
    const githubToken: string = body.github_token || "";
    const filename: string = body.filename || ""; // e.g. "functions/aiCommandCentre.ts"
    const patchedCode: string = body.patched_code || ""; // full file content after fix
    const issueTitle: string = body.issue_title || "AI Self-Debug Fix";
    const issueDescription: string = body.issue_description || "Automated patch generated by Self-Debug AI";
    const severity: string = body.severity || "minor"; // critical | major | minor

    if (!githubToken || !filename || !patchedCode) {
      return new Response(JSON.stringify({
        success: false,
        error: "Missing required fields: github_token, filename, patched_code",
      }), { status: 400, headers: { "Content-Type": "application/json" } });
    }

    const now = new Date().toISOString();
    const timestamp = now.replace(/[:.]/g, "-").substring(0, 19);
    const branchName = `fix/ai-debug-${timestamp}`;
    const safeName = filename.replace(/\//g, "-").replace(/\./g, "_");

    // Step 1 — Get main branch SHA
    const mainRef = await ghRequest("/git/ref/heads/main", "GET", githubToken);
    const mainSha: string = mainRef?.object?.sha;
    if (!mainSha) {
      throw new Error("Could not get main branch SHA: " + JSON.stringify(mainRef));
    }

    // Step 2 — Create new branch from main
    const branchResult = await ghRequest("/git/refs", "POST", githubToken, {
      ref: `refs/heads/${branchName}`,
      sha: mainSha,
    });
    if (branchResult.message && branchResult.message !== "ok") {
      // Branch may already exist, continue
    }

    // Step 3 — Get current file SHA (needed to update existing file)
    const fileInfo = await ghRequest(`/contents/${filename}?ref=main`, "GET", githubToken);
    const fileSha: string | undefined = fileInfo?.sha;

    // Step 4 — Encode patched code to base64
    const encoder = new TextEncoder();
    const encoded = encoder.encode(patchedCode);
    let base64Content = "";
    const chunk = 8192;
    for (let i = 0; i < encoded.length; i += chunk) {
      base64Content += btoa(String.fromCharCode(...encoded.slice(i, i + chunk)));
    }

    // Step 5 — Commit the patched file to the new branch
    const commitPayload: Record<string, unknown> = {
      message: `fix(${severity}): ${issueTitle}\n\nAuto-generated by Simpee Self-Debug AI\nTimestamp: ${now}`,
      content: base64Content,
      branch: branchName,
    };
    if (fileSha) commitPayload.sha = fileSha;

    const commitResult = await ghRequest(`/contents/${filename}`, "PUT", githubToken, commitPayload);
    if (!commitResult?.content) {
      throw new Error("Failed to commit file: " + JSON.stringify(commitResult).substring(0, 200));
    }

    // Step 6 — Open Pull Request
    const prBody = [
      `## 🤖 AI Self-Debug Fix`,
      ``,
      `**Severity:** ${severity.toUpperCase()}`,
      `**File:** \`${filename}\``,
      `**Issue:** ${issueTitle}`,
      ``,
      `### Description`,
      issueDescription,
      ``,
      `### Changes`,
      `- Patched \`${filename}\` with AI-generated fix`,
      `- Branch: \`${branchName}\``,
      ``,
      `### Review`,
      `- [ ] CodeRabbit QC review`,
      `- [ ] Simpee (Orchestrator) validation`,
      `- [ ] Copilot (Validator) final gate`,
      ``,
      `> Generated by Simpee Orchestrator | Nexus Command v1.6`,
      `> Timestamp: ${now}`,
    ].join("\n");

    const prResult = await ghRequest("/pulls", "POST", githubToken, {
      title: `[AI-FIX][${severity.toUpperCase()}] ${issueTitle}`,
      body: prBody,
      head: branchName,
      base: "main",
      draft: false,
    });

    const prUrl: string = prResult?.html_url || "";
    const prNumber: number = prResult?.number || 0;

    if (!prUrl) {
      throw new Error("PR creation failed: " + JSON.stringify(prResult).substring(0, 200));
    }

    // Step 7 — Log to Nexus Command TestLog
    await postToNexus("TestLog", {
      checkpoint: "AUTO_PR_OPENED",
      status: "pass",
      notes: `Pull Request #${prNumber} opened automatically by Self-Debug AI.\n\nFile: ${filename}\nBranch: ${branchName}\nPR URL: ${prUrl}\nSeverity: ${severity}\nIssue: ${issueTitle}\n\nCodeRabbit will review this PR automatically.`,
      simpee_validated: true,
      copilot_validated: false,
      timestamp: now,
    });

    // Step 8 — Post notification to SChatMessage
    await postToNexus("SChatMessage", {
      sender: "Simpee",
      sender_type: "agent",
      message: `🔀 AUTO PR OPENED\n\nPR #${prNumber}: [${severity.toUpperCase()}] ${issueTitle}\nFile: ${filename}\nBranch: ${branchName}\n\nCodeRabbit is reviewing now ✅\n\nPR: ${prUrl}`,
      timestamp: now,
      session_id: `pr-${prNumber}`,
      read: false,
    });

    return new Response(JSON.stringify({
      success: true,
      pr_number: prNumber,
      pr_url: prUrl,
      branch: branchName,
      file: filename,
      severity,
      message: `PR #${prNumber} opened. CodeRabbit will review automatically.`,
    }), { headers: { "Content-Type": "application/json" } });

  } catch (err: any) {
    return new Response(JSON.stringify({
      success: false,
      error: err.message,
    }), { status: 500, headers: { "Content-Type": "application/json" } });
  }
}
